<a href="https://colab.research.google.com/github/jiteshkumarkumar/Python/blob/main/Real%20World/Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
updated = files.upload()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("realworld_sales_dataset.csv")
df

Saving realworld_sales_dataset.csv to realworld_sales_dataset (1).csv


OrderID   OrderDate ShipmentDate  CustomerName     Category Region  \
0        1152  2024-07-27   2024-08-04  Customer_327  Electronics   West   
1         500  2024-02-23   2024-03-04  Customer_426  Electronics  North   
2        1337  2022-04-27   2022-05-06  Customer_379  Electronics   East   
3        1033  2022-02-24   2022-03-02  Customer_381         Food   West   
4         281  2023-11-16   2023-11-19  Customer_208    Furniture  South   
...       ...         ...          ...           ...          ...    ...   
1995      894  2022-06-05   2022-06-08  Customer_247    Furniture  South   
1996     1837  2024-03-30   2024-04-08  Customer_427         Food  North   
1997     1702  2023-06-01   2023-06-07  Customer_135    Furniture   East   
1998      957  2024-02-14   2024-02-19   Customer_64    Furniture   West   
1999      939  2024-12-13   2024-12-22   Customer_25  Electronics  North   

        Channel  Quantity  UnitPrice  DiscountApplied  SalesAmount  
0     Wholesale        15     271.72             True     3668.220  
1        Online        17     433.52            False     7369.840  
2        Retail         6     434.97            False     2609.820  
3     Wholesale        12     283.51             True     3061.908  
4        Retail        15      49.16             True      663.660  
...         ...       ...        ...              ...          ...  
1995  Wholesale         6     248.45            False     1490.700  
1996  Wholesale        16     194.62             True     2802.528  
1997     Online         6     118.02            False      708.120  
1998     Online         6     487.15             True     2630.610  
1999  Wholesale        14     136.99            False     1917.860  

[2000 rows x 11 columns]

**Clean the data & Assign Correct data types of each columns of the DataFrame**

In [ ]:
df.shape  # check the columns and rows count
#df.size  # total records in the data frame
print('DataFrame shape', df.shape)

DataFrame shape (2000, 11)


In [ ]:
df.columns=df.columns.str.lower()

In [ ]:
#check data types and null valuesmb
df.info()
df.dtypes   #check data types
# FOUND:  Need to convert date to correct data types, it is ob

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   orderid          2000 non-null   int64  
 1   orderdate        2000 non-null   object 
 2   shipmentdate     2000 non-null   object 
 3   customername     2000 non-null   object 
 4   category         2000 non-null   object 
 5   region           2000 non-null   object 
 6   channel          2000 non-null   object 
 7   quantity         2000 non-null   int64  
 8   unitprice        2000 non-null   float64
 9   discountapplied  2000 non-null   bool   
 10  salesamount      2000 non-null   float64
dtypes: bool(1), float64(2), int64(2), object(6)
memory usage: 158.3+ KB


orderid              int64
orderdate           object
shipmentdate        object
customername        object
category            object
region              object
channel             object
quantity             int64
unitprice          float64
discountapplied       bool
salesamount        float64
dtype: object

In [ ]:
df['orderdate']=pd.to_datetime(df['orderdate'],format='%Y-%m-%d')
df['shipmentdate']=pd.to_datetime(df['shipmentdate'],format='%Y-%m-%d')

# convert string into date data type
df[['orderdate','shipmentdate']].dtypes

orderdate       datetime64[ns]
shipmentdate    datetime64[ns]
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   orderid          2000 non-null   int64         
 1   orderdate        2000 non-null   datetime64[ns]
 2   shipmentdate     2000 non-null   datetime64[ns]
 3   customername     2000 non-null   object        
 4   category         2000 non-null   object        
 5   region           2000 non-null   object        
 6   channel          2000 non-null   object        
 7   quantity         2000 non-null   int64         
 8   unitprice        2000 non-null   float64       
 9   discountapplied  2000 non-null   bool          
 10  salesamount      2000 non-null   float64       
dtypes: bool(1), datetime64[ns](2), float64(2), int64(2), object(4)
memory usage: 158.3+ KB


In [ ]:
df.duplicated().sum()   # check duplicate in the data fram and there is no duplicate value
df.isna().sum()   # there is no null value in the dataframe

orderid            0
orderdate          0
shipmentdate       0
customername       0
category           0
region             0
channel            0
quantity           0
unitprice          0
discountapplied    0
salesamount        0
dtype: int64

In [ ]:
# Data analysis based on date & time

df['orderyear']=df['orderdate'].dt.year
df['ordermonth']=df['orderdate'].dt.month_name()
#If there is a missing and invalid data in the date column
df['orderdate'] = pd.to_datetime(df['orderdate'],errors='coerce')
df['shipmentdate']=pd.to_datetime(df['shipmentdate'],errors = 'coerce')
df['processingtime'] = df['shipmentdate'] - df['orderdate']


In [ ]:
# Find the proceessing time to delivery a order
df['processingtime']=df['shipmentdate'] - df['orderdate']
df['processingtime'].dt.days

# converting datetime data type into int to perform numpy calculation on the column
df['processingtime'].dt.days
#np.average(df['processingtime'])

df['processingtime']=df['processingtime'].dt.days

In [ ]:
df['dayname'] = df['orderdate'].dt.day_name()

In [ ]:
df_arry = df['customername'].unique()
len(df_arry)
print('Unique Customer Count', len(df_arry) )   # Need to find the most loyal customers last

print('First Order Received', min(df['orderdate']))
print('Last Order Received',max(df['orderdate']))

Unique Customer Count 489
First Order Received 2022-01-01 00:00:00
Last Order Received 2024-12-31 00:00:00


In [ ]:
# describe analysis
df.describe()
df.describe(include='O')
df.describe(include='all')
#df.describe(include='datetime')

orderid                   orderdate  \
count   2000.000000                        2000   
unique          NaN                         NaN   
top             NaN                         NaN   
freq            NaN                         NaN   
mean    1000.500000  2023-07-12 13:27:50.400000   
min        1.000000         2022-01-01 00:00:00   
25%      500.750000         2022-10-12 00:00:00   
50%     1000.500000         2023-07-27 00:00:00   
75%     1500.250000         2024-04-10 06:00:00   
max     2000.000000         2024-12-31 00:00:00   
std      577.494589                         NaN   

                         shipmentdate  customername  category region channel  \
count                            2000          2000      2000   2000    2000   
unique                            NaN           489         4      4       3   
top                               NaN  Customer_208  Clothing  South  Online   
freq                              NaN            11       524    532     727   
mean    2023-07-18 00:30:57.599999744           NaN       NaN    NaN     NaN   
min               2022-01-04 00:00:00           NaN       NaN    NaN     NaN   
25%               2022-10-16 18:00:00           NaN       NaN    NaN     NaN   
50%               2023-08-01 00:00:00           NaN       NaN    NaN     NaN   
75%               2024-04-15 06:00:00           NaN       NaN    NaN     NaN   
max               2025-01-07 00:00:00           NaN       NaN    NaN     NaN   
std                               NaN           NaN       NaN    NaN     NaN   

           quantity    unitprice discountapplied  salesamount    orderyear  \
count   2000.000000  2000.000000            2000  2000.000000  2000.000000   
unique          NaN          NaN               2          NaN          NaN   
top             NaN          NaN            True          NaN          NaN   
freq            NaN          NaN            1009          NaN          NaN   
mean      10.195500   253.750990             NaN  2458.940332  2023.036000   
min        1.000000     5.120000             NaN     6.550000  2022.000000   
25%        5.750000   130.815000             NaN   812.524500  2022.000000   
50%       10.000000   253.375000             NaN  1901.762500  2023.000000   
75%       15.000000   376.955000             NaN  3679.098000  2024.000000   
max       19.000000   499.840000             NaN  9059.010000  2024.000000   
std        5.419868   141.864924             NaN  2024.978250     0.822826   

       ordermonth  processingtime dayname  
count        2000     2000.000000    2000  
unique         12             NaN       7  
top       January             NaN  Friday  
freq          185             NaN     307  
mean          NaN        5.460500     NaN  
min           NaN        1.000000     NaN  
25%           NaN        3.000000     NaN  
50%           NaN        5.000000     NaN  
75%           NaN        8.000000     NaN  
max           NaN       10.000000     NaN  
std           NaN        2.860337     NaN

**That's a very broad topic! Exploratory Data Analysis (EDA) Of Real World Data**



1.   **KPI of Real World data:**

>  Total Order,
>  Sold Unite sold,
>  Total Revenue, total discount provided,

2.   **Customer spending**
>  Average spending on a order,
>  Average discount provide on a order



In [ ]:

print(f"Total Order Received:        {np.count_nonzero(df.orderid)} orders")
print(f"Total Unite Sold:            {np.sum(df['quantity'])} Unites")
print(f"Total Revenue Generated:     {np.sum(df['salesamount']).round(2)} ")
#print(f"Total Discount Provided:     {np.sum(df['discount']).round(2)} ")
print('Avg time to deliver a order', np.average(df['processingtime']))
print(f"Customer Average Spending On A Order: {(df['salesamount'].sum()/df['orderid'].count()).round(2)} ")

# KPI: percentage of rows where discountapplied == True
yes_percentage = (df['discountapplied'].sum() / len(df)) * 100
print(f"Total Discount approvided : {yes_percentage:.2f}%")


Total Order Received:        2000 orders
Total Unite Sold:            20391 Unites
Total Revenue Generated:     4917880.66 
Avg time to deliver a order 5.4605
Customer Average Spending On A Order: 2458.94 
Total Discount approvided : 50.45%


In [ ]:
# total Revenue by Region
df.groupby('region').agg(Total_revenue = ('salesamount','sum'),Total_order = ('orderid','count')).sort_values('Total_revenue',ascending=False)

Total_revenue  Total_order
region                            
South     1290042.846          532
North     1215308.663          482
West      1208848.462          484
East      1203680.693          502

In [ ]:
# The total revenue and order count by category
df.groupby('category').agg(Total_revenue =('salesamount','sum'), Total_order =('orderid','count')).round(2)

Total_revenue  Total_order
category                               
Clothing        1284500.65          524
Electronics     1317491.97          509
Food            1120211.56          488
Furniture       1195676.48          479

from matplotlib import pyplot as plt
_df_0['Total_revenue'].plot(kind='hist', bins=20, title='Total_revenue')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Total_order'].plot(kind='hist', bins=20, title='Total_order')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2.plot(kind='scatter', x='Total_revenue', y='Total_order', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Total_revenue'].plot(kind='line', figsize=(8, 4), title='Total_revenue')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_4['Total_order'].plot(kind='line', figsize=(8, 4), title='Total_order')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
# Weekly Order received
df.groupby('dayname', as_index= False)['orderid'].count().sort_values('orderid', ascending=False)

dayname  orderid
0     Friday      307
5    Tuesday      290
4   Thursday      290
6  Wednesday      289
2   Saturday      280
3     Sunday      280
1     Monday      264

from matplotlib import pyplot as plt
_df_10['orderid'].plot(kind='hist', bins=20, title='orderid')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_11.groupby('dayname').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_12['orderid'].plot(kind='line', figsize=(8, 4), title='orderid')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:



Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.




from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['dayname'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='orderid', y='dayname', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
#Monthly order trend
result = df.groupby('ordermonth', as_index=False).agg(Total_order=('orderid','count'))

month_order =[
     'January', 'February', 'March', 'April', 'May', 'June',
     'July', 'August', 'September', 'October', 'November', 'December']

result['ordermonth']=pd.Categorical(result['ordermonth'], categories=month_order,ordered=True)
result = result.sort_values('ordermonth')
print(result)

   ordermonth  Total_order
4     January          185
3    February          164
7       March          169
0       April          170
8         May          176
6        June          150
5        July          154
1      August          176
11  September          151
10    October          168
9    November          159
2    December          178


In [ ]:
# Channel
df.groupby('channel').agg(order_count=('orderid','count'),Total_Revenue=('salesamount','sum')).sort_values('order_count',ascending=False)

order_count  Total_Revenue
channel                              
Online             727    1835313.407
Retail             641    1509483.500
Wholesale          632    1573083.757

>**OBSERVATIONS**

**KPI**

* We Received total 2000 orders From January 1, 2022 to December 31,2024

* Sold out total during the time period 20391 Unites.

* Time Peirod Generated Total Revenue $4917880.66

* It took Avg time to deliver a order 5.4605.

* Customer Average Spending range On A Order $2458.94.

* Provided Almost 50.45% Product discount. We Need to control providing discount on the product.  

**Analysis**

The South Region was the primary revenue driver and volume leader this period, generating $1.29M from 532 orders. This performance sets a strong benchmark; we should investigate key success factors and replicate top strategies in other regions

The Electronics category achieved the highest overall revenue ($\mathbf{\$1,317,491.97}$). Crucially, it did so with only 509 orders (the second-lowest volume).  This suggests the category is driven by high-value products, successful upselling/cross-selling, or premium pricing, making each transaction highly profitable.

The most significant finding from this analysis is the remarkable consistency in order volume across all seven days of the week. The difference between the peak day (Friday, 307 orders) and the trough day (Monday, 264 orders) is only 43 orders (a variance of approximately 14%).

The most notable trend is the clear dip in order volume during the early summer months, with June (150 orders) and September (151 orders) representing the lowest figures for the entire year. Conversely, the year begins and ends strongly, peaking in January (185 orders) and holding strong in December (178 orders).

* Insight: The 19% drop from the January peak (185) to the June trough (150) suggests a distinct seasonality in customer demand that severely impacts summer performance. This seasonal fluctuation is the largest variance point in the entire dataset.

* Actionable Strategy: We must initiate a deep-dive into the successful marketing and promotional strategies deployed in January and December. The goal is to adapt these successful Q4/Q1 campaigns to specifically counteract the slump experienced in Q3 (June, July, September), focusing on revitalizing demand during the low-performing summer period.

The Online channel is the undisputed volume leader, driving the highest number of orders (727) and the largest gross revenue ($1.83M). However, the Wholesale channel, despite having the lowest order volume (632), generates a superior Average Order Value (AOV):

* Online AOV: $2,524.40 per order

* Wholesale AOV: $2,488.90 per order

* Retail AOV: $2,354.89 per order